import type { Metadata } from 'next'
import { Vibur, Nunito } from 'next/font/google'
import './globals.css'
import Header from '@/components/layers/header'

const nunito = Nunito({
  variable: '--font-nunito',
  weight: ['200', '300', '400', '500', '600', '700', '800', '900', '1000'],
  subsets: ['latin'],
})

const vibur = Vibur({
  variable: '--font-vibur',
  weight: ['400'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${vibur.variable} antialiased min-h-[100svh] px-4 bg-amber-500 bg-[url('/bg/bg-kid-space.svg')] bg-center bg-size-[300px] bg-repeat font-body`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
