import type { Metadata } from 'next'
import Header from '@/components/layers/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Header />
      <main className="flex flex-col gap-30 items-center">{children}</main>
    </>
  )
}
