name: Deploy to cPanel

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AW_ENDPOINT: ${{ secrets.AW_ENDPOINT }} # Une clé API sécurisée
      AW_PROJECT_ID: ${{ secrets.AW_PROJECT_ID }} # Une clé API sécurisée
      AW_SECRET_KEY: ${{ secrets.AW_SECRET_KEY }} # Une clé API sécurisée
      AW_DATABASE_ID: ${{ secrets.AW_DATABASE_ID }} # Une clé API sécurisée
      AW_ENTRIES_COLLECTION_ID: ${{ secrets.AW_ENTRIES_COLLECTION_ID }} # Une clé API sécurisée
      AW_USERS_COLLECTION_ID: ${{ secrets.AW_USERS_COLLECTION_ID }} # Une clé API sécurisée
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }} # Une clé API sécurisée
      RESEND_VERIFIED_DOMAIN: ${{ secrets.RESEND_VERIFIED_DOMAIN }} # Une clé API sécurisée

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0' # ou la version nécessaire pour ton projet

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ${{ secrets.FTP_SERVER }} # Adresse de ton serveur cPanel
          username: ${{ secrets.FTP_USERNAME }} # Nom d'utilisateur FTP
          password: ${{ secrets.FTP_PASSWORD }} # Mot de passe FTP
          server-dir: /taraficotouille.antoine-g.com/ # Chemin sur le serveur cPanel où déployer
